version: "3"
services:
  pulsar:
    image: apachepulsar/pulsar:3.1.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:8080
      - 127.0.0.1:6650:6650
    environment:
      PULSAR_MEM: ' -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g'
    command: bin/pulsar standalone
